<%@ Page Title="Log In" Language="C#" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="ATMOS_SROM.Account.Login" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head id="Head1" runat="server">
    <title></title>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        .page
        {
            width: 370px;
            margin: 100px auto 0px auto;
            background-color: #ebebeb;
        }
        div.accountInfo
        {
            width: 100%;
        }
        .main
        {
            padding: 10px 12px;
            margin: 12px 8px 8px 8px;
            min-height: 220px;
        }
    </style>
</head>
<body>
    <form id="Form1" runat="server" autocomplete="off">
    <div class="page">
        <div class="header">
            <div class="title">
                <h1>
                    ATMOS
                </h1>
            </div>
            <div class="loginDisplay">
            </div>
            <div class="clear hideSkiplink">
            </div>
        </div>
        <div class="main">
            <div id="DivMessage" runat="server" visible="false">
            </div>
            <asp:ValidationSummary ID="LoginUserValidationSummary" runat="server" CssClass="failureNotification"
                ValidationGroup="LoginUserValidationGroup" />
            <p>
                <asp:Label ID="UserNameLabel" runat="server" AssociatedControlID="UserName">Username:</asp:Label>
                <asp:TextBox ID="UserName" runat="server" CssClass="textEntry"></asp:TextBox>
                <asp:RequiredFieldValidator ID="UserNameRequired" runat="server" ControlToValidate="UserName"
                    CssClass="failureNotification" ErrorMessage="User Name is required." ToolTip="User Name is required."
                    ValidationGroup="LoginUserValidationGroup">*</asp:RequiredFieldValidator>
            </p>
            <p>
                <asp:Label ID="PasswordLabel" runat="server" AssociatedControlID="Password">Password:</asp:Label>
                <asp:TextBox ID="Password" runat="server" CssClass="passwordEntry" TextMode="Password"></asp:TextBox>
                <asp:RequiredFieldValidator ID="PasswordRequired" runat="server" ControlToValidate="Password"
                    CssClass="failureNotification" ErrorMessage="Password is required." ToolTip="Password is required."
                    ValidationGroup="LoginUserValidationGroup">*</asp:RequiredFieldValidator>
            </p>
            <p class="submitButton">
                <asp:Button ID="Button1" runat="server" Text="Login" Width="100PX" OnClick="btnLoginClick" />
            </p>
            <hr />
            <p style="font-size:x-small;">
                All records and data generated by or residing upon this system,
                or the systems to which it grants access, are the property of 707.
                You are authorized to use this system, and those to which it grants access, for
                approved business purposes only. Use for any other purpose is prohibited.  
                Any activities may be monitored.
            </p>
            <br />
        </div>
    </div>
    <div class="clear">
    </div>
    <div class="footer">
    </div>
    </form>
</body>
</html>
